<a href="https://colab.research.google.com/github/SarhadGautam/AI_Steel_Hackathon_Sarhad/blob/PetProjects/Tata_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/SarhadGautam/AI_Steel_Hackathon_Sarhad.git

Cloning into 'AI_Steel_Hackathon_Sarhad'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 18 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (18/18), 645.29 KiB | 5.81 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [2]:
%cd AI_Steel_Hackathon_Sarhad
%cd dataset

/content/AI_Steel_Hackathon_Sarhad
/content/AI_Steel_Hackathon_Sarhad/dataset

In [3]:
import os
import pandas as pd
import numpy as np


#print(os.getcwd())
print(os.listdir())
pd.set_option(
    'display.float_format',
    '{:.2f}'.format
)

['sample_submission.csv', 'test.csv', 'train.csv']

In [4]:
train_df = pd.read_csv('train.csv', index_col = 'CoilID')
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1352 entries, 487 to 465
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      1352 non-null   float64
 1   X2      1352 non-null   float64
 2   X3      1352 non-null   float64
 3   X4      1352 non-null   float64
 4   X5      1352 non-null   float64
 5   X6      1352 non-null   float64
 6   X7      1352 non-null   float64
 7   X8      1351 non-null   float64
 8   X9      1352 non-null   float64
 9   X10     1346 non-null   float64
 10  X11     1352 non-null   float64
 11  X12     1352 non-null   float64
 12  X13     1352 non-null   float64
 13  X14     1352 non-null   float64
 14  X15     1192 non-null   float64
 15  X16     1346 non-null   float64
 16  X17     1352 non-null   float64
 17  X18     1352 non-null   float64
 18  X19     1352 non-null   float64
 19  X20     1352 non-null   float64
 20  X21     1351 non-null   float64
 21  X22     1352 non-null   float64
 22  X23     1346 non-null   float64
 23  X24     1346 non-null   float64
 24  X25     1346 non-null   float64
 25  X26     1345 non-null   float64
 26  X27     1346 non-null   float64
 27  X28     1352 non-null   float64
 28  X29     1352 non-null   float64
 29  X30     1352 non-null   float64
 30  X31     1352 non-null   float64
 31  X32     1352 non-null   float64
 32  X33     1352 non-null   float64
 33  X34     1352 non-null   float64
 34  X35     1352 non-null   float64
 35  X36     1352 non-null   float64
 36  X37     1352 non-null   float64
 37  X38     1352 non-null   float64
 38  X39     1352 non-null   float64
 39  X40     1352 non-null   float64
 40  X41     1352 non-null   float64
 41  X42     1321 non-null   float64
 42  X43     1352 non-null   float64
 43  X44     1352 non-null   float64
 44  X45     1352 non-null   float64
 45  X46     1352 non-null   float64
 46  X47     1352 non-null   float64
 47  X48     1339 non-null   float64
 48  X49     1352 non-null   float64
 49  Y       1352 non-null   float64
dtypes: float64(50)
memory usage: 538.7 KB

In [5]:
train_df['Y'].value_counts(normalize=True)*100

Y
0.00   95.12
1.00    4.88
Name: proportion, dtype: float64

In [6]:
#train_df.agg(['min', 'max', 'count', 'sum', 'median', ('mode', lambda x: x.mode().iloc[0])]).T -- doesnt work
#train_df.agg(['min', 'max', 'count', 'sum', 'median']).T.assign(mode=train_df.mode().iloc[0])
#train_df.agg(['min', 'max', 'count', 'sum', 'median']).T.assign(mode=train_df.apply(lambda x: ', '.join(map(str, round(x.mode(),2)))))
# mode above doesnt yield in any meaningful inference so dropping it altogether.
data_summary = train_df.agg(['min', 'max', 'count', 'sum', 'median', 'std']).T
data_summary['q25'] = train_df.quantile(.25)
data_summary['q50'] = train_df.quantile(.50)
data_summary['q75'] = train_df.quantile(.75)
data_summary['skeww'] = train_df.skew()
data_summary

,min,max,count,sum,median,std,q25,q50,q75,skeww
X1,235.25,1124.90,1352.00,1391093.52,1071.98,108.51,1009.28,1071.98,1092.03,-2.71
X2,96.76,1148.17,1352.00,777906.40,589.16,232.10,405.53,589.16,725.77,0.04
X3,124.15,1026.92,1352.00,727880.01,548.04,135.29,441.59,548.04,632.24,-0.23
X4,575.92,755.98,1352.00,936364.02,724.97,56.80,622.21,724.97,734.45,-0.80
X5,559.27,763.26,1352.00,877462.65,661.17,35.40,625.33,661.17,668.05,-0.27
X6,529.94,742.73,1352.00,836326.34,615.24,45.60,583.36,615.24,659.56,-0.11
X7,439.22,618.95,1352.00,715533.91,547.65,46.26,476.81,547.65,554.58,-0.51
X8,425.41,575.31,1351.00,714368.34,545.40,40.22,520.19,545.40,556.33,-1.08
X9,343.11,505.35,1352.00,624218.22,482.41,40.60,423.60,482.41,488.71,-1.19
X10,1.12,12.31,1346.00,9246.74,7.00,2.63,4.70,7.00,8.97,-0.10
X11,24.00,40.00,1352.00,43561.00,32.00,3.33,30.00,32.00,35.00,0.08
X12,-2.32,98.44,1352.00,65044.11,47.82,9.62,43.23,47.82,51.97,0.46
X13,97.08,1631.92,1352.00,1174774.26,842.06,397.30,545.83,842.06,1169.88,0.15
X14,538.36,660.37,1352.00,810872.92,602.22,30.99,573.67,602.22,627.98,-0.16
X15,1.17,12.33,1192.00,4122.24,2.74,2.21,2.05,2.74,4.07,2.22
X16,-0.92,39.01,1346.00,30922.81,22.92,3.90,20.35,22.92,25.54,-0.20
X17,1089.90,1207.81,1352.00,1564976.51,1158.74,14.42,1149.61,1158.74,1166.89,-0.46
X18,858.75,918.08,1352.00,1204009.84,890.03,7.99,887.17,890.03,896.49,-0.09
X19,911.11,1743.05,1352.00,1836316.87,1281.37,142.48,1262.87,1281.37,1512.59,0.58
X20,166.46,1065.12,1352.00,772284.53,576.63,124.54,490.46,576.63,661.76,-0.32
X21,357.82,1108.93,1351.00,914192.17,679.02,90.98,629.91,679.02,722.44,0.42
X22,68.53,1027.50,1352.00,809485.19,635.44,165.55,524.97,635.44,704.96,-0.90
X23,-0.27,41.27,1346.00,38659.31,28.51,4.04,26.17,28.51,31.19,-0.49
X24,-1.26,30.79,1346.00,22017.47,16.95,4.99,14.71,16.95,19.37,-1.72
X25,-0.46,24.50,1346.00,21653.58,15.83,3.13,13.76,15.83,18.35,0.06
X26,-0.02,16.92,1345.00,17767.53,13.38,1.48,12.44,13.38,14.13,-1.98
X27,-0.17,14.05,1346.00,13935.77,10.48,1.33,9.65,10.48,11.20,-1.15
X28,4.32,6.64,1352.00,6421.61,4.54,0.60,4.48,4.54,4.65,2.49
X29,4.58,10.25,1352.00,9394.26,6.91,1.09,6.23,6.91,7.83,-0.09
X30,4.36,14.91,1352.00,13649.21,10.12,2.25,8.77,10.12,11.77,-0.36
X31,5.88,20.29,1352.00,18261.43,13.85,3.26,11.12,13.85,15.90,-0.25
X32,6.51,24.51,1352.00,21629.91,16.30,3.78,13.47,16.30,19.72,-0.60
X33,6.71,25.23,1352.00,23146.10,19.05,3.67,14.92,19.05,19.98,-1.02
X34,0.00,4380.00,1352.00,3189946.00,3487.00,1770.22,90.00,3487.00,3861.25,-0.46
X35,0.00,17740669.00,1352.00,13415153943.00,13940342.00,6665497.38,462725.75,13940342.00,14889261.50,-0.73
X36,0.00,4296.00,1352.00,3081599.00,3559.50,1767.39,98.75,3559.50,3865.25,-0.32
X37,0.00,4457.00,1352.00,2218948.00,553.00,1741.16,45.00,553.00,3756.25,0.39
X38,0.00,4155.00,1352.00,933552.00,74.50,1263.55,0.00,74.50,613.75,1.87
X39,98.00,173.00,1352.00,219404.00,164.00,11.37,160.00,164.00,169.00,-3.81
X40,56.00,72.00,1352.00,83659.00,62.00,3.84,58.00,62.00,62.00,0.67
X41,0.08,1.38,1352.00,792.12,0.57,0.30,0.37,0.57,0.80,0.19
X42,0.00,0.06,1321.00,14.97,0.00,0.02,0.00,0.00,0.01,1.66
X43,0.03,0.41,1352.00,380.30,0.29,0.07,0.24,0.29,0.33,-0.99
X44,0.00,0.33,1352.00,123.70,0.08,0.07,0.03,0.08,0.14,0.68
X45,-82.67,120.17,1352.00,15557.95,9.18,25.00,-1.37,9.18,24.20,0.25
X46,0.00,0.06,1352.00,3.71,0.00,0.01,0.00,0.00,0.00,7.48
X47,0.02,0.42,1352.00,68.83,0.05,0.04,0.04,0.05,0.05,7.40
X48,0.00,0.05,1339.00,9.52,0.00,0.01,0.00,0.00,0.00,1.58
X49,0.00,0.25,1352.00,87.07,0.06,0.05,0.02,0.06,0.11,0.63
Y,0.00,1.00,1352.00,66.00,0.00,0.22,0.00,0.00,0.00,4.19

In [7]:
null_summary = pd.DataFrame({
    'null_count': train_df.isnull().sum(),
    'null_pct': (train_df.isnull().mean()*100)
})
null_summary[null_summary['null_pct'] > 0.00].index

# Number of missing rows are less compared to the number of records here I will take the columns too with missing rows

Index(['X8', 'X10', 'X15', 'X16', 'X21', 'X23', 'X24', 'X25', 'X26', 'X27',
       'X42', 'X48'],
      dtype='object')

In [8]:
# Returns rows with missing data in those columns
null_columns = ['X8', 'X10', 'X15', 'X16', 'X21', 'X23', 'X24', 'X25', 'X26', 'X27',
       'X42', 'X48']
null_records = train_df[train_df[null_columns].isnull().any(axis=1)]
train_df.isnull().sum(
    axis=1
).describe()

count   1352.00
mean       0.18
std        0.62
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        8.00
dtype: float64

In [9]:
train_df.isnull().sum(
    axis=1
).value_counts().sort_index()

0    1159
1     172
2      12
3       3
7       4
8       2
Name: count, dtype: int64

In [10]:
null_pattern_table = (train_df[null_columns]
                      .isnull()
                      .value_counts()
                      .reset_index(name='count')
)
null_pattern_table['num_nulls'] = (null_pattern_table[null_columns].sum(axis=1))

null_pattern_table['pct'] = (((null_pattern_table['count']/len(train_df))*100)
.round(2))

null_pattern_table

,X8,X10,X15,X16,X21,X23,X24,X25,X26,X27,X42,X48,count,num_nulls,pct
0,False,False,False,False,False,False,False,False,False,False,False,False,1159,0,85.72
1,False,False,True,False,False,False,False,False,False,False,False,False,155,1,11.46
2,False,False,False,False,False,False,False,False,False,False,True,False,17,1,1.26
3,False,False,False,False,False,False,False,False,False,False,True,True,11,2,0.81
4,False,True,False,True,False,True,True,True,True,True,False,False,4,7,0.30
5,False,True,True,True,False,True,True,True,True,True,False,False,2,8,0.15
6,False,False,True,False,False,False,False,False,False,False,True,True,2,3,0.15
7,False,False,True,False,False,False,False,False,False,False,True,False,1,2,0.07
8,True,False,False,False,True,False,False,False,True,False,False,False,1,3,0.07

In [11]:
null_records_df = train_df.loc[train_df[null_columns].isnull().any(axis=1),null_columns].sort_index()
null_records_df

           X8  X10   X15   X16    X21   X23   X24   X25   X26   X27  X42  X48
CoilID
745    537.73 6.42  3.03 17.06 636.65 24.14 18.00 12.69 13.36 10.58  NaN  NaN
750    516.67 6.36  3.12 20.17 698.56 24.77 16.49 14.25 13.65  9.56  NaN 0.00
752    479.32 4.44  4.95 16.18 689.91 23.18 11.37 12.29 10.93  8.15  NaN  NaN
753    472.78 4.71  3.92 16.83 660.26 24.64 12.11 12.51 11.52  8.90  NaN  NaN
754    485.77 4.82  4.02 16.58 663.91 24.38 12.23 12.08 11.34  8.55  NaN  NaN
...       ...  ...   ...   ...    ...   ...   ...   ...   ...   ...  ...  ...
1625   441.36 2.92   NaN 29.10 722.52 34.13 -1.26 18.53 15.61 11.17 0.02 0.04
1626   437.82 1.84   NaN 28.45 854.40 34.45 -0.22 19.24 16.05 11.38 0.02 0.04
1628   440.50 2.28   NaN 30.40 743.04 34.49  0.42 18.56 15.66 11.24 0.02 0.04
1629   457.35  NaN   NaN   NaN 728.00   NaN   NaN   NaN   NaN   NaN 0.02 0.04
1674   447.29  NaN 11.69   NaN 709.89   NaN   NaN   NaN   NaN   NaN 0.06 0.00

[193 rows x 12 columns]

In [14]:
pd.crosstab(
    train_df['X8'].isnull(),
    train_df['Y'],
    normalize='columns'
)

Y      0.00  1.00
X8
False  1.00  1.00
True   0.00  0.00

In [12]:
train_df['X8_missing'] = (train_df['X8'].isnull().astype(int))